"""
analyze_clusters.py – Verify K-Means Climate Ecosystems

This script analyzes the 'region_stats.csv' generated by the preprocessing pipeline
to confirm the physical meaning and homogeneity of the 10 K-Means clusters.
It outputs a statistical summary to the console and generates visual boxplots.
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATS_PATH = os.path.join(ROOT, "data", "processed", "region_stats.csv")
OUTPUT_PLOT = os.path.join(ROOT, "cluster_distributions.png")
OUTPUT_PAIRPLOT = os.path.join(ROOT, "cluster_pairplot.png")

def main():
    if not os.path.exists(STATS_PATH):
        print(f"[Error] File not found: {STATS_PATH}")
        print("Please run src/preprocess.py first.")
        return

    print("=" * 80)
    print("K-Means Climate Ecosystem Analysis")
    print("=" * 80)

    # 1. Load Data
    df = pd.read_csv(STATS_PATH)
    print(f"Loaded {len(df)} regions.")
    
    features = ["score_mean", "score_zero_prob", "score_std", "tmp_mean", "prec_mean"]

    # 2. Tabular Summary
    print("\n[1] Cluster Centroids (Mean values per ecosystem):")
    summary = df.groupby("cluster_id").agg(
        region_count=("region_id", "count"),
        **{feat: (feat, "mean") for feat in features}
    ).round(4)
    
    # Sort by score_mean to physically order them from "Wettest" to "Driest"
    summary = summary.sort_values("score_mean")
    print(summary.to_string())

    # 3. Homogeneity Check (Standard Deviation within clusters)
    print("\n[2] Cluster Homogeneity (Standard Deviation WITHIN each ecosystem):")
    print("    (Lower values mean regions inside the cluster are highly similar)")
    std_summary = df.groupby("cluster_id")[features].std().round(4)
    std_summary = std_summary.loc[summary.index] # Align index with the sorted summary
    print(std_summary.to_string())

    # 4. Visualizations: Boxplots
    print("\n[3] Generating Boxplots for distribution spread...")
    sns.set_theme(style="whitegrid")
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    axes = axes.flatten()

    for i, feat in enumerate(features):
        # Order the x-axis by the sorted severity
        sns.boxplot(
            x="cluster_id", 
            y=feat, 
            data=df, 
            ax=axes[i], 
            order=summary.index,
            palette="viridis"
        )
        axes[i].set_title(f"Distribution of {feat}", fontsize=14, fontweight='bold')
        axes[i].set_xlabel("Cluster ID (Ordered by Severity)")
        axes[i].set_ylabel(feat)

    # Remove the empty 6th subplot
    fig.delaxes(axes[5])
    plt.tight_layout()
    plt.savefig(OUTPUT_PLOT, dpi=300)
    print(f"    Saved -> {OUTPUT_PLOT}")

    # 5. Visualizations: Pairplot (Optional but highly insightful)
    print("[4] Generating Scatter Pairplot (This might take a few seconds)...")
    # We map the cluster_id to string to force categorical coloring
    df_plot = df.copy()
    df_plot["cluster_id"] = df_plot["cluster_id"].astype(str)
    
    pair_fig = sns.pairplot(
        df_plot, 
        vars=["score_zero_prob", "tmp_mean", "prec_mean"], 
        hue="cluster_id", 
        corner=True,
        palette="tab10",
        plot_kws={'alpha': 0.6, 's': 15}
    )
    pair_fig.figure.suptitle("Ecosystem Feature Interactions", y=1.02, fontsize=16, fontweight='bold')
    pair_fig.savefig(OUTPUT_PAIRPLOT, dpi=300)
    print(f"    Saved -> {OUTPUT_PAIRPLOT}")

    print("\nAnalysis complete. Please inspect the generated PNG files.")
    print("=" * 80)

if __name__ == "__main__":
    main()